name: Automated Issue Responses

on:
  issues:
    types: [opened, labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Automated Comment on Issue Creation
        if: github.event.action == 'opened'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueComment = `Hello @${{ github.actor }}, we have received your feedback and are reviewing it. \n Your reports on HTML issues help our developers prioritize improvements to our HTML conversion process, helping make arXiv more accessible. Thank you! \nPlease note that:\n • We receive a high volume of reports – while we track, review, and assess each issue reported, we cannot respond to reporters individually.\n • This GitHub repository ONLY tracks reports that are about the experimental HTML format – if you report an issue that is not relevant to HTML rendering, it will not be noted or tracked. \n • For issues that are not relevant to HTML rendering (e.g. issues that also appear in the PDF) please contact the author (for issues like typos or deadlinks) or submit a ticket to the arXiv user support portal (http://arxiv.org/support/general_help). `;
            github.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            })

      # - name: Automated Comment on Label
      #   if: github.event.action == 'labeled'
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       const labelName = ${{ github.event.label.name }};
      #       const commentBody = getCannedResponseForLabel(labelName);
            
      #       # Define a function to get the appropriate canned response for a label
      #       function getCannedResponseForLabel(label) {
      #         # You would need to define your mapping of labels to canned responses
      #         const cannedResponses = {
      #           'bug': 'This issue has been marked as a bug. Our team will look into it shortly.',
      #           'enhancement': 'This issue has been marked for enhancement. We are evaluating the suggestions.',
      #           'fidelity': 'Misc mistakes and bugs in the produced HTML',
      #           'front matter': 'Title page metadata and related content',
      #           'figure': 'General image issues: too big, too small, position, and etc.',
      #           # Add other labels and responses as needed
      #           'default': 'Thank you for your contribution! We will review it soon.'
      #         };
      #         return cannedResponses[label] || cannedResponses['default'];
      #       }
            
      #       # Leave a comment with the canned response
      #       if (commentBody) {
      #         github.issues.createComment({
      #           issue_number: ${{ github.event.issue.number }},
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           body: commentBody
      #         });
      #       }
